# Generated by Django 2.2.7 on 2020-05-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('finish_date', models.DateTimeField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('sname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=254)),
                ('events', models.ManyToManyField(to='eventhandler.Event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='author',
            field=models.OneToOneField(on_delete='CASCADE', to='eventhandler.User'),
        ),
    ]
