# Generated by Django 2.2.7 on 2020-05-01 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventhandler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
