# Generated by Django 2.2.7 on 2020-05-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventhandler', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.CharField(max_length=25),
        ),
    ]
