# Generated by Django 2.2.7 on 2020-05-02 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventhandler', '0005_event_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='author',
        ),
    ]
