# Generated by Django 2.2.7 on 2020-05-02 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventhandler', '0007_event_denis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='denis',
        ),
    ]
