# Generated by Django 2.2.7 on 2020-05-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventhandler', '0009_event_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='author_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
