# Generated by Django 2.2.7 on 2020-05-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventhandler', '0010_event_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='added_date',
            field=models.DateField(auto_now=True),
        ),
    ]
